site_name: SecretManagement.PasswordState
repo_url: https://example.com
remote_branch: gh-pages
remote_name: SecretManagement.PasswordStateGitHub
theme:
    name: readthedocs

nav:
    - Home: index.md
    - About: about_SecretManagement.PasswordState.help.md
