name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Default Build
      shell: pwsh
      run: ./build.ps1 -Task default -Bootstrap

